# Display name of workflow
name: 01_Chaining Jobs

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  push:
    branches: [main]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      run-job-4:
        description: "DEPLOY TO PRODUCTION"
        required: true
        type: boolean

jobs:
  job-1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Output for Job 1
        run: echo "DEPLOYED!"

  job-2:
    name: Unit Test
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output for Job 2
        run: echo "TESTED!"
      # - name: Make Job 2 Failed
       # run: exit 1
    
  job-3:
    name: Staging
    runs-on: ubuntu-latest
    needs:
      - job-2
    steps:
      - name: Output for Job 3
        run: echo "STAGING DEPLOYED!"

  job-4:
    name: Production
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run-job-4 == 'true'
    # if: always()
    needs: job-3
    runs-on: ubuntu-latest
    steps:
      - name: Output for Job 4
        run: echo "PRODUCTION DEPLOYED!"
