# Display name of workflow
name: 01_Chaining Jobs

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      run-job-3:
        description: "Run job 3"
        required: true
        type: boolean

jobs:
  job-1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Output for Job 1
        run: echo "Hello from Job 1. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"

  job-2:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output for Job 2
        run: echo "Hello from Job 2"
      # - name: Make Job 2 Failed
       # run: exit 1
    
  job-3:
    name: Staging
    if: github.event.inputs.run-job-3 == 'true'
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - name: Output for Job 3
        run: echo "Hello from Job 3"

  job-4:
    name: Production
    if: github.event_name == 'workflow_dispatch'
    # if: always()       - one of 2 or 3 job must finished
    needs: [job-2, job-3]
    runs-on: ubuntu-latest
    steps:
      - name: Output for Job 4
        run: echo "Hello from Job 4"
