name: myTestWorkflow

env:
  VAR01: workflow_VAR01
  VAR02: workflow_VAR02
  VAR03: workflow_VAR03

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Somebody to greet'
        default: Jozef
        required: true
        type: string
      city:
        description: "The favourite city"
        required: true
        default: "Regensburg"
        type: choice
        options:
        - Regensburg
        - Bratislava
        - New York
        - Miami
      color:
        description: "Is your favourite color GREEN?"
        required: true
        type: boolean
      
jobs:
  job-01:
    env:
      VAR02: jobs_VAR02
      VAR03: jobs_VAR03
    runs-on: 
      ubuntu-latest
    steps:
    - name: Write the Person to greet
      env:
        VAR03: step_VAR03
      run: |
        echo "Input from Workflow: ${{ github.event.inputs.name }}"
        echo 'You done it good!'
        echo $VAR01
        echo $VAR02
        echo $VAR03
        
  job-02:
    runs-on:
      ubuntu-latest
    needs:
      job-01
    steps:
    - name: 'Write the favourite city'
      run: echo "Your favourite city ${{ github.event.inputs.city }}"
    - name: "Fake Job Issue"
      run: exit 1

  job-03:
    # if: ${{ github.event.inputs.color }}
    if: always()
    runs-on:
      ubuntu-latest
    needs:
      job-02
    steps:
    - name: 'Check the favourite color'
      run: echo "Green is your favourite color ${{ github.event.inputs.color }}"
    
