name: myTestWorkflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Somebody to greet'
        default: Alabama
        required: true
        type: string

jobs:
  job-01:
    runs-on: 
      ubuntu-latest
    steps:
    - name: Write the City name
      run: |
        echo 'Input from Workflow: ${{ github.event.inputs.name }}'
        echo 'You done it good!'
